name: PHP Code Style (Pint)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: '8.3'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Run Laravel Pint
        run: vendor/bin/pint --test